version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    ports:
      - 8081:8081
    environment:
      - aaa=hoge