version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=tcp(echo-practice_db_1)
      - DB_NAME=development
      - DB_OPTIONS=?charset=utf8&parseTime=true

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 13306:3306

volumes:
  db-data: null
